name: commit build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '**/src/**/*.rs'
      - '**/README.md'
      - 'mod.ts'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Prettier core crate
        working-directory: core
        run: cargo fmt
      - name: Prettier node crate
        working-directory: node
        run: cargo fmt
      - name: Prettier wasm crate
        working-directory: wasm
        run: cargo fmt
      - name: Minify mod.ts code
        run: npm run minify
      - name: Update README.md
        run: npm run readme
      - name: Build wasm
        working-directory: wasm
        run: |
          cargo install wasm-pack
          wasm-pack build --no-typescript --release -t web
          mv ./pkg/decancer_wasm_bg.wasm ./bin/decancer.wasm
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update files on commit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
